Create a CI template for workflows that require dependent infrustructure
Particular/.github pull request #1
Opened 2021-07-20 17:51 UTC by kentdr

2021-07-20 18:42 UTC, kbaley commented on workflow-templates/ci-with-dependencies.properties.yml
> +  resources such as Azure or AWS credentials.",
```suggestion
  dependencies. This template is necessary if the build/test pipeline requires use of secrets 
  such as Azure or AWS credentials.",

```

2021-07-20 18:42 UTC, kbaley commented on workflow-templates/ci-with-dependencies.yml
> +      - name: Setup Infrustructure # This name can be changed to be more specific.
```suggestion
      - name: Setup Infrustructure # Change this name to be more specific.

```

2021-07-20 18:42 UTC, kbaley commented on workflow-templates/ci-with-dependencies.yml
> +        # It is advisable to check for error conditions and ensure that the dependent infrustrucure is available and running before moving to the next step.
```suggestion
        # Check for error conditions and ensure that the dependent infrastructure is available and running before moving to the next step.

```

2021-07-20 18:42 UTC, kbaley commented on workflow-templates/ci-with-dependencies.yml
> +        # Any output parameters specified in the setup stage can be accessed by using {{steps.setup-infrustrucutre.outputs.key}}
```suggestion
        # Any output parameters specified in the setup stage can be accessed by using {{steps.setup-infrastructure.outputs.key}}         

```

2021-07-20 18:42 UTC, kbaley commented on workflow-templates/ci-with-dependencies.yml
> +        id: setup-infrustructure # This name can be changed to be more specific. This name is used when referencing output parameters.
```suggestion
        id: setup-infrastructure # This name can be changed to be more specific. This name is used when referencing output parameters.

```

2021-07-20 18:42 UTC, kbaley commented on workflow-templates/ci-with-dependencies.yml
> +        # Provide a PowerShell script that will initialize dependent infrustructure.
```suggestion
        # Provide a PowerShell script that will initialize dependent infrastructure. 

```

2021-07-20 18:42 UTC, kbaley commented on workflow-templates/ci-with-dependencies.yml
> +      - name: Teardown Infrustructure
```suggestion
      - name: Teardown Infrastructure

```

2021-07-20 18:42 UTC, kbaley commented on workflow-templates/ci-with-dependencies.properties.yml
> +  "description": "A CI workflow template to build and test packages that have infrustructure
```suggestion
  "description": "A CI workflow template to build and test packages that have infrastructure 

```

2021-07-20 19:42 UTC, DavidBoike requested changes

2021-07-20 19:42 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.properties.yml
> +  such as Azure or AWS credentials.",
What's going on with the newlines. Is that even allowed?

2021-07-20 19:42 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +      - name: Setup Infrustructure # Change this name to be more specific.
Spelling, but also, we started out naming things specifically and it turned into a real drag as we copied things between repos. Easier to just leave everything as "infrastructure" and then not change it.
```suggestion
      - name: Setup Infrastructure
```

2021-07-20 19:42 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +
Specifically DON'T change it, especially the ID, because then you get into the trap of changing this but forgetting to change it in the cleanup. Easiest to leave it alone.
```suggestion
        id: setup-infrastructure
```

2021-07-20 19:42 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +        # Provide a PowerShell script that will initialize dependent infrastructure.
I'd like to see the boilerplate for discovering the Azure region of the GitHub Actions runner in here. Quotas we have in ACI, for example, are predicated on distributing the work amongst multiple regions, and the lower latency we have the better/faster things are going to run.

2021-07-20 19:42 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +        # Provide a PowerShell script that will shutdown/clean up any dependent infustrucutre that has been setup.
```suggestion
        # Provide a PowerShell script that will shutdown/clean up any dependent infrastructure that has been set up.

```

2021-07-20 20:06 UTC, kentdr commented on workflow-templates/ci-with-dependencies.yml
> +        # Provide a PowerShell script that will initialize dependent infrastructure.
Is there a general assumption that if we're using this template we will be using Azure in some way?  If so we don't need to comment out the login block above, and adding the boilerplate for the region makes more sense.

2021-07-20 21:31 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +        # Provide a PowerShell script that will initialize dependent infrastructure.
Pretty strong yes. If we're using an Azure resource, or a containerized service that we deploy to ACI, that means we're using Azure. And GitHub Actions runners are hosted in Azure. That's going to be 90% of the time at least. The only time we're not going to be doing that is, for example, in a completely AWS-based service like SQS (currently our only example) where then the person implementing the CI workflow will probably be smart enough to just remove the unnecessary Azure stuff.

2021-07-21 15:15 UTC, kentdr commented on workflow-templates/ci-with-dependencies.yml
> +        # Provide a PowerShell script that will initialize dependent infrastructure.
I added the boilerplate and some extra comments.  Also uncommented out the Azure login step

2021-07-21 19:44 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +        uses: actions/setup-dotnet@v1.7.2
```suggestion
        uses: actions/setup-dotnet@v1.8.1
```

2021-07-21 19:44 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +        uses: actions/setup-dotnet@v1.7.2
```suggestion
        uses: actions/setup-dotnet@v1.8.1
```

2021-07-21 19:44 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +        # Output parameters can be set for future steps to use by using the echo ::set-output name=key::value command.
Pretty sure this needs to be indented so that it's a PowerShell comment and not a YAML comment. YAML you so silly. 🤷‍♂️
```suggestion
          # Retrieve the Azure region in which this workflow is running. This region should be used to create addtional resources.
          $hostInfo = curl -H Metadata:true "169.254.169.254/metadata/instance?api-version=2017-08-01" | ConvertFrom-Json
          $region = $hostInfo.compute.location

          # Provide a PowerShell script that will initialize dependent infrastructure. Use the GitHubActions-RG resource group for all resources.
          # Check for error conditions and ensure that the dependent infrastructure is available and running before moving to the next step.
          # Output parameters can be set for future steps to use by using the echo ::set-output name=key::value command.

```

2021-07-21 19:44 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +        run:
Needs this character to turn it into a multi-line value
```suggestion
        run: |
```

2021-07-21 19:44 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +        # Any output parameters specified in the setup stage can be accessed by using {{steps.setup-infrastructure.outputs.key}}
```suggestion
        run: |
          # Provide a PowerShell script that will shutdown/clean up any dependent infrastructure that has been set up.
          # Any output parameters specified in the setup stage can be accessed by using {{steps.setup-infrastructure.outputs.key}}
```

2021-07-21 19:44 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +
```suggestion
```

2021-07-21 19:44 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +      - name: Teardown Infrastructure
```suggestion
      - name: Teardown infrastructure
```

2021-07-21 19:44 UTC, DavidBoike commented on workflow-templates/ci-with-dependencies.yml
> +      - name: Setup Infrastructure
```suggestion
      - name: Setup infrastructure
```

2021-07-22 14:15 UTC, DavidBoike approved these changes

2021-07-22 14:24 UTC, kbaley commented on workflow-templates/ci-with-dependencies.yml
> +      - name: Setup infrastructure
I wouldn't mind changing the name to something like `Setup --INSERT NAME OF INFRASTRUCTURE--` so that it's clearer to someone setting up that they should change this to something less generic and make it easier for a future reader to see what's going on.

2021-07-22 14:50 UTC, merged